services:
  - type: web
    name: metier-backend
    region: singapore
    env: node
    plan: free
    buildCommand: npm install --prefix backend && npm --prefix backend run prisma:generate && npm --prefix backend run prisma:migrate:deploy && npm --prefix backend run build
    startCommand: npm --prefix backend run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001

  - type: web
    name: metier-frontend
    region: singapore
    env: node
    plan: free
    buildCommand: npm install --prefix frontend && npm --prefix frontend run build
    startCommand: npm --prefix frontend run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://metier-backend-n9k2.onrender.com
      - key: PORT
        value: 3000
